; DEBUG: DAG con 50 libros:
; prerequisitos on
; paralelos on
; npaginas off
; Fichero generado con el programa, seed 18
(define (problem Libros-base)
	(:domain Lectura)
	(:objects
		Casper Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre - mes
		Libro0 Libro1 Libro2 Libro3 Libro4 Libro5 Libro6 Libro7 Libro8 Libro9 Libro10 Libro11 Libro12 Libro13 Libro14 Libro15 Libro16 Libro17 Libro18 Libro19 Libro20 Libro21 Libro22 Libro23 Libro24 Libro25 Libro26 Libro27 Libro28 Libro29 Libro30 Libro31 Libro32 Libro33 Libro34 Libro35 Libro36 Libro37 Libro38 Libro39 Libro40 Libro41 Libro42 Libro43 Libro44 Libro45 Libro46 Libro47 Libro48 Libro49 - libro
	)

	(:init
		; Datos universales
		(inm_anterior Casper Enero) (inm_anterior Enero Febrero) (inm_anterior Febrero Marzo) (inm_anterior Marzo Abril) (inm_anterior Abril Mayo) (inm_anterior Mayo Junio) (inm_anterior Junio Julio) (inm_anterior Julio Agosto) (inm_anterior Agosto Septiembre) (inm_anterior Septiembre Octubre) (inm_anterior Octubre Noviembre) (inm_anterior Noviembre Diciembre) 
		(anterior Enero Febrero) (anterior Enero Marzo) (anterior Enero Abril) (anterior Enero Mayo) (anterior Enero Junio) (anterior Enero Julio) (anterior Enero Agosto) (anterior Enero Septiembre) (anterior Enero Octubre) (anterior Enero Noviembre) (anterior Enero Diciembre) (anterior Febrero Marzo) (anterior Febrero Abril) (anterior Febrero Mayo) (anterior Febrero Junio) (anterior Febrero Julio) (anterior Febrero Agosto) (anterior Febrero Septiembre) (anterior Febrero Octubre) (anterior Febrero Noviembre) (anterior Febrero Diciembre) (anterior Marzo Abril) (anterior Marzo Mayo) (anterior Marzo Junio) (anterior Marzo Julio) (anterior Marzo Agosto) (anterior Marzo Septiembre) (anterior Marzo Octubre) (anterior Marzo Noviembre) (anterior Marzo Diciembre) (anterior Abril Mayo) (anterior Abril Junio) (anterior Abril Julio) (anterior Abril Agosto) (anterior Abril Septiembre) (anterior Abril Octubre) (anterior Abril Noviembre) (anterior Abril Diciembre) (anterior Mayo Junio) (anterior Mayo Julio) (anterior Mayo Agosto) (anterior Mayo Septiembre) (anterior Mayo Octubre) (anterior Mayo Noviembre) (anterior Mayo Diciembre) (anterior Junio Julio) (anterior Junio Agosto) (anterior Junio Septiembre) (anterior Junio Octubre) (anterior Junio Noviembre) (anterior Junio Diciembre) (anterior Julio Agosto) (anterior Julio Septiembre) (anterior Julio Octubre) (anterior Julio Noviembre) (anterior Julio Diciembre) (anterior Agosto Septiembre) (anterior Agosto Octubre) (anterior Agosto Noviembre) (anterior Agosto Diciembre) (anterior Septiembre Octubre) (anterior Septiembre Noviembre) (anterior Septiembre Diciembre) (anterior Octubre Noviembre) (anterior Octubre Diciembre) (anterior Noviembre Diciembre) 
		; Relaciones entre objetos
		(leido Libro16)
		(leido Libro21)
		(leido Libro30)
		(quiere_leer Libro0)
		(quiere_leer Libro1)
		(quiere_leer Libro2)
		(quiere_leer Libro3)
		(quiere_leer Libro4)
		(quiere_leer Libro5)
		(quiere_leer Libro7)
		(quiere_leer Libro8)
		(quiere_leer Libro11)
		(quiere_leer Libro12)
		(quiere_leer Libro13)
		(quiere_leer Libro14)
		(quiere_leer Libro15)
		(quiere_leer Libro18)
		(quiere_leer Libro19)
		(quiere_leer Libro20)
		(quiere_leer Libro22)
		(quiere_leer Libro23)
		(quiere_leer Libro24)
		(quiere_leer Libro26)
		(quiere_leer Libro27)
		(quiere_leer Libro28)
		(quiere_leer Libro29)
		(quiere_leer Libro31)
		(quiere_leer Libro32)
		(quiere_leer Libro33)
		(quiere_leer Libro34)
		(quiere_leer Libro35)
		(quiere_leer Libro36)
		(quiere_leer Libro37)
		(quiere_leer Libro38)
		(quiere_leer Libro39)
		(quiere_leer Libro41)
		(quiere_leer Libro42)
		(quiere_leer Libro43)
		(quiere_leer Libro44)
		(quiere_leer Libro45)
		(quiere_leer Libro47)
		(quiere_leer Libro49)
		(predecesor Libro0 Libro12)
		(predecesor Libro1 Libro33)
		(predecesor Libro2 Libro4)
		(predecesor Libro3 Libro44)
		(predecesor Libro4 Libro10)
		(predecesor Libro5 Libro11)
		(predecesor Libro6 Libro42)
		(predecesor Libro8 Libro26)
		(predecesor Libro9 Libro18)
		(predecesor Libro10 Libro28)
		(predecesor Libro11 Libro24)
		(predecesor Libro13 Libro46)
		(predecesor Libro14 Libro20)
		(predecesor Libro15 Libro32)
		(predecesor Libro16 Libro19)
		(predecesor Libro17 Libro35)
		(predecesor Libro18 Libro22)
		(predecesor Libro19 Libro43)
		(predecesor Libro20 Libro49)
		(predecesor Libro21 Libro37)
		(predecesor Libro22 Libro25)
		(predecesor Libro24 Libro29)
		(predecesor Libro26 Libro36)
		(predecesor Libro28 Libro39)
		(predecesor Libro29 Libro40)
		(predecesor Libro37 Libro47)
		(predecesor Libro47 Libro48)
		(paralelo Libro0 Libro5)
		(paralelo Libro5 Libro0)
		(paralelo Libro1 Libro12)
		(paralelo Libro12 Libro1)
		(paralelo Libro3 Libro36)
		(paralelo Libro36 Libro3)
		(paralelo Libro4 Libro17)
		(paralelo Libro17 Libro4)
		(paralelo Libro6 Libro24)
		(paralelo Libro24 Libro6)
		(paralelo Libro7 Libro42)
		(paralelo Libro42 Libro7)
		(paralelo Libro8 Libro17)
		(paralelo Libro17 Libro8)
		(paralelo Libro9 Libro14)
		(paralelo Libro14 Libro9)
		(paralelo Libro10 Libro48)
		(paralelo Libro48 Libro10)
		(paralelo Libro11 Libro13)
		(paralelo Libro13 Libro11)
		(paralelo Libro14 Libro41)
		(paralelo Libro41 Libro14)
		(paralelo Libro16 Libro47)
		(paralelo Libro47 Libro16)
		(paralelo Libro19 Libro39)
		(paralelo Libro39 Libro19)
		(paralelo Libro20 Libro21)
		(paralelo Libro21 Libro20)
		(paralelo Libro20 Libro26)
		(paralelo Libro26 Libro20)
		(paralelo Libro23 Libro30)
		(paralelo Libro30 Libro23)
		(paralelo Libro25 Libro46)
		(paralelo Libro46 Libro25)
		(paralelo Libro29 Libro35)
		(paralelo Libro35 Libro29)
		(paralelo Libro31 Libro37)
		(paralelo Libro37 Libro31)
		(paralelo Libro32 Libro33)
		(paralelo Libro33 Libro32)
		(paralelo Libro44 Libro45)
		(paralelo Libro45 Libro44)
	)

	(:goal
		; Para todos los libros que se quieren leer, asignados.
		(forall (?l - libro) (imply (quiere_leer ?l) (asignado ?l)))
	)
)
