; DEBUG: DAG con 32 libros:
; prerequisitos on
; paralelos on
; npaginas on
; Fichero generado con el programa, seed 104
(define (problem Libros-base)
	(:domain Lectura)
	(:objects
		Casper Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre - mes
		Libro0 Libro1 Libro2 Libro3 Libro4 Libro5 Libro6 Libro7 Libro8 Libro9 Libro10 Libro11 Libro12 Libro13 Libro14 Libro15 Libro16 Libro17 Libro18 Libro19 Libro20 Libro21 Libro22 Libro23 Libro24 Libro25 Libro26 Libro27 Libro28 Libro29 Libro30 Libro31 - libro
	)

	(:init
		; Datos universales
		(inm_anterior Casper Enero) (inm_anterior Enero Febrero) (inm_anterior Febrero Marzo) (inm_anterior Marzo Abril) (inm_anterior Abril Mayo) (inm_anterior Mayo Junio) (inm_anterior Junio Julio) (inm_anterior Julio Agosto) (inm_anterior Agosto Septiembre) (inm_anterior Septiembre Octubre) (inm_anterior Octubre Noviembre) (inm_anterior Noviembre Diciembre) 
		(anterior Enero Febrero) (anterior Enero Marzo) (anterior Enero Abril) (anterior Enero Mayo) (anterior Enero Junio) (anterior Enero Julio) (anterior Enero Agosto) (anterior Enero Septiembre) (anterior Enero Octubre) (anterior Enero Noviembre) (anterior Enero Diciembre) (anterior Febrero Marzo) (anterior Febrero Abril) (anterior Febrero Mayo) (anterior Febrero Junio) (anterior Febrero Julio) (anterior Febrero Agosto) (anterior Febrero Septiembre) (anterior Febrero Octubre) (anterior Febrero Noviembre) (anterior Febrero Diciembre) (anterior Marzo Abril) (anterior Marzo Mayo) (anterior Marzo Junio) (anterior Marzo Julio) (anterior Marzo Agosto) (anterior Marzo Septiembre) (anterior Marzo Octubre) (anterior Marzo Noviembre) (anterior Marzo Diciembre) (anterior Abril Mayo) (anterior Abril Junio) (anterior Abril Julio) (anterior Abril Agosto) (anterior Abril Septiembre) (anterior Abril Octubre) (anterior Abril Noviembre) (anterior Abril Diciembre) (anterior Mayo Junio) (anterior Mayo Julio) (anterior Mayo Agosto) (anterior Mayo Septiembre) (anterior Mayo Octubre) (anterior Mayo Noviembre) (anterior Mayo Diciembre) (anterior Junio Julio) (anterior Junio Agosto) (anterior Junio Septiembre) (anterior Junio Octubre) (anterior Junio Noviembre) (anterior Junio Diciembre) (anterior Julio Agosto) (anterior Julio Septiembre) (anterior Julio Octubre) (anterior Julio Noviembre) (anterior Julio Diciembre) (anterior Agosto Septiembre) (anterior Agosto Octubre) (anterior Agosto Noviembre) (anterior Agosto Diciembre) (anterior Septiembre Octubre) (anterior Septiembre Noviembre) (anterior Septiembre Diciembre) (anterior Octubre Noviembre) (anterior Octubre Diciembre) (anterior Noviembre Diciembre) 
		(= (paginas-leidas Enero) 0)
		(= (paginas-leidas Febrero) 0)
		(= (paginas-leidas Marzo) 0)
		(= (paginas-leidas Abril) 0)
		(= (paginas-leidas Mayo) 0)
		(= (paginas-leidas Junio) 0)
		(= (paginas-leidas Julio) 0)
		(= (paginas-leidas Agosto) 0)
		(= (paginas-leidas Septiembre) 0)
		(= (paginas-leidas Octubre) 0)
		(= (paginas-leidas Noviembre) 0)
		(= (paginas-leidas Diciembre) 0)
		; Relaciones entre objetos
		(leido Libro5)
		(quiere_leer Libro0)
		(quiere_leer Libro1)
		(quiere_leer Libro3)
		(quiere_leer Libro4)
		(quiere_leer Libro7)
		(quiere_leer Libro8)
		(quiere_leer Libro9)
		(quiere_leer Libro10)
		(quiere_leer Libro12)
		(quiere_leer Libro13)
		(quiere_leer Libro14)
		(quiere_leer Libro16)
		(quiere_leer Libro17)
		(quiere_leer Libro18)
		(quiere_leer Libro19)
		(quiere_leer Libro20)
		(quiere_leer Libro21)
		(quiere_leer Libro22)
		(quiere_leer Libro23)
		(quiere_leer Libro24)
		(quiere_leer Libro25)
		(quiere_leer Libro26)
		(quiere_leer Libro27)
		(quiere_leer Libro28)
		(quiere_leer Libro29)
		(quiere_leer Libro30)
		(quiere_leer Libro31)
		(predecesor Libro0 Libro23)
		(predecesor Libro2 Libro6)
		(predecesor Libro3 Libro11)
		(predecesor Libro4 Libro10)
		(predecesor Libro5 Libro30)
		(predecesor Libro6 Libro8)
		(predecesor Libro8 Libro15)
		(predecesor Libro10 Libro24)
		(predecesor Libro12 Libro29)
		(predecesor Libro13 Libro14)
		(predecesor Libro20 Libro22)
		(predecesor Libro22 Libro26)
		(predecesor Libro27 Libro28)
		(paralelo Libro1 Libro9)
		(paralelo Libro9 Libro1)
		(paralelo Libro1 Libro10)
		(paralelo Libro10 Libro1)
		(paralelo Libro2 Libro3)
		(paralelo Libro3 Libro2)
		(paralelo Libro4 Libro6)
		(paralelo Libro6 Libro4)
		(paralelo Libro5 Libro19)
		(paralelo Libro19 Libro5)
		(paralelo Libro7 Libro14)
		(paralelo Libro14 Libro7)
		(paralelo Libro8 Libro20)
		(paralelo Libro20 Libro8)
		(paralelo Libro12 Libro20)
		(paralelo Libro20 Libro12)
		(paralelo Libro13 Libro23)
		(paralelo Libro23 Libro13)
		(paralelo Libro15 Libro31)
		(paralelo Libro31 Libro15)
		(= (paginas Libro0) 106)
		(= (paginas Libro1) 78)
		(= (paginas Libro2) 92)
		(= (paginas Libro3) 114)
		(= (paginas Libro4) 151)
		(= (paginas Libro5) 28)
		(= (paginas Libro6) 72)
		(= (paginas Libro7) 124)
		(= (paginas Libro8) 65)
		(= (paginas Libro9) 119)
		(= (paginas Libro10) 139)
		(= (paginas Libro11) 107)
		(= (paginas Libro12) 100)
		(= (paginas Libro13) 115)
		(= (paginas Libro14) 147)
		(= (paginas Libro15) 154)
		(= (paginas Libro16) 81)
		(= (paginas Libro17) 33)
		(= (paginas Libro18) 66)
		(= (paginas Libro19) 146)
		(= (paginas Libro20) 27)
		(= (paginas Libro21) 177)
		(= (paginas Libro22) 102)
		(= (paginas Libro23) 51)
		(= (paginas Libro24) 24)
		(= (paginas Libro25) 72)
		(= (paginas Libro26) 95)
		(= (paginas Libro27) 52)
		(= (paginas Libro28) 161)
		(= (paginas Libro29) 163)
		(= (paginas Libro30) 160)
		(= (paginas Libro31) 101)
	)

	(:goal
		; Para todos los libros que se quieren leer, asignados.
		(forall (?l - libro) (imply (quiere_leer ?l) (asignado ?l)))
	)
)
