; DEBUG: DAG con 15 libros:
; prerequisitos on
; paralelos on
; npaginas on
; Fichero generado con el programa, seed 1704571405
(define (problem Libros-base)
	(:domain Lectura)
	(:objects
		Casper Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre - mes
		Libro0 Libro1 Libro2 Libro3 Libro5 Libro6 Libro7 Libro9 Libro10 Libro12 Libro14 Libro4 Libro8 Libro11 Libro13 - libro
	)

	(:init
		; Datos universales
		(inm_anterior Casper Enero) (inm_anterior Enero Febrero) (inm_anterior Febrero Marzo) (inm_anterior Marzo Abril) (inm_anterior Abril Mayo) (inm_anterior Mayo Junio) (inm_anterior Junio Julio) (inm_anterior Julio Agosto) (inm_anterior Agosto Septiembre) (inm_anterior Septiembre Octubre) (inm_anterior Octubre Noviembre) (inm_anterior Noviembre Diciembre) 
		(anterior Enero Febrero) (anterior Enero Marzo) (anterior Enero Abril) (anterior Enero Mayo) (anterior Enero Junio) (anterior Enero Julio) (anterior Enero Agosto) (anterior Enero Septiembre) (anterior Enero Octubre) (anterior Enero Noviembre) (anterior Enero Diciembre) (anterior Febrero Marzo) (anterior Febrero Abril) (anterior Febrero Mayo) (anterior Febrero Junio) (anterior Febrero Julio) (anterior Febrero Agosto) (anterior Febrero Septiembre) (anterior Febrero Octubre) (anterior Febrero Noviembre) (anterior Febrero Diciembre) (anterior Marzo Abril) (anterior Marzo Mayo) (anterior Marzo Junio) (anterior Marzo Julio) (anterior Marzo Agosto) (anterior Marzo Septiembre) (anterior Marzo Octubre) (anterior Marzo Noviembre) (anterior Marzo Diciembre) (anterior Abril Mayo) (anterior Abril Junio) (anterior Abril Julio) (anterior Abril Agosto) (anterior Abril Septiembre) (anterior Abril Octubre) (anterior Abril Noviembre) (anterior Abril Diciembre) (anterior Mayo Junio) (anterior Mayo Julio) (anterior Mayo Agosto) (anterior Mayo Septiembre) (anterior Mayo Octubre) (anterior Mayo Noviembre) (anterior Mayo Diciembre) (anterior Junio Julio) (anterior Junio Agosto) (anterior Junio Septiembre) (anterior Junio Octubre) (anterior Junio Noviembre) (anterior Junio Diciembre) (anterior Julio Agosto) (anterior Julio Septiembre) (anterior Julio Octubre) (anterior Julio Noviembre) (anterior Julio Diciembre) (anterior Agosto Septiembre) (anterior Agosto Octubre) (anterior Agosto Noviembre) (anterior Agosto Diciembre) (anterior Septiembre Octubre) (anterior Septiembre Noviembre) (anterior Septiembre Diciembre) (anterior Octubre Noviembre) (anterior Octubre Diciembre) (anterior Noviembre Diciembre) 
		(= (paginas-leidas Enero) 0)
		(= (paginas-leidas Febrero) 0)
		(= (paginas-leidas Marzo) 0)
		(= (paginas-leidas Abril) 0)
		(= (paginas-leidas Mayo) 0)
		(= (paginas-leidas Junio) 0)
		(= (paginas-leidas Julio) 0)
		(= (paginas-leidas Agosto) 0)
		(= (paginas-leidas Septiembre) 0)
		(= (paginas-leidas Octubre) 0)
		(= (paginas-leidas Noviembre) 0)
		(= (paginas-leidas Diciembre) 0)
		; Relaciones entre objetos
		(leido Libro11)
		(leido Libro13)
		(predecesor Libro0 Libro6)
		(predecesor Libro1 Libro5)
		(predecesor Libro5 Libro7)
		(predecesor Libro8 Libro10)
		(paralelo Libro0 Libro1)
		(paralelo Libro1 Libro0)
		(paralelo Libro0 Libro3)
		(paralelo Libro3 Libro0)
		(paralelo Libro2 Libro9)
		(paralelo Libro9 Libro2)
		(paralelo Libro6 Libro7)
		(paralelo Libro7 Libro6)
		(paralelo Libro8 Libro11)
		(paralelo Libro11 Libro8)
		(paralelo Libro12 Libro14)
		(paralelo Libro14 Libro12)
		(= (paginas Libro0) 0)
		(= (paginas Libro1) 0)
		(= (paginas Libro2) 0)
		(= (paginas Libro3) 0)
		(= (paginas Libro4) 0)
		(= (paginas Libro5) 0)
		(= (paginas Libro6) 0)
		(= (paginas Libro7) 0)
		(= (paginas Libro8) 0)
		(= (paginas Libro9) 0)
		(= (paginas Libro10) 0)
		(= (paginas Libro11) 0)
		(= (paginas Libro12) 0)
		(= (paginas Libro13) 0)
		(= (paginas Libro14) 0)
		(quiere_leer Libro0)
		(quiere_leer Libro1)
		(quiere_leer Libro2)
		(quiere_leer Libro3)
		(quiere_leer Libro5)
		(quiere_leer Libro6)
		(quiere_leer Libro7)
		(quiere_leer Libro9)
		(quiere_leer Libro10)
		(quiere_leer Libro12)
		(quiere_leer Libro14)
	)

	(:goal
		; Para todos los libros que se quieren leer, asignados. Para los paralelos a los asignados, ya leidos o asignados
		(and (forall (?l - libro) (imply (quiere_leer ?l) (asignado ?l)))
			  ; (forall (?l - libro ?par - libro) (imply (and (asignado ?l) (paralelo ?l ?par)) (or (asignado ?par) (leido ?par))))
		)
	)
)
