; Fichero generado con el programa, seed (de momento NULL)
(define (problem Libros-base)
	(:domain Lectura)
	(:objects
		Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre - mes
		Libro3 - quiereL
		Libro0 Libro1 Libro2 Libro4 Libro5 Libro6 Libro7 Libro8 Libro9 - otrosL
	)

	(:init
		; Datos universales
		(inm_anterior Enero Febrero)
		(inm_anterior Febrero Marzo)
		(inm_anterior Marzo Abril)
		(inm_anterior Abril Mayo)
		(inm_anterior Mayo Junio)
		(inm_anterior Junio Julio)
		(inm_anterior Julio Agosto)
		(inm_anterior Agosto Septiembre)
		(inm_anterior Septiembre Octubre)
		(inm_anterior Octubre Noviembre)
		(inm_anterior Noviembre Diciembre)
		(anterior Enero Febrero)
		(anterior Enero Marzo)
		(anterior Enero Abril)
		(anterior Enero Mayo)
		(anterior Enero Junio)
		(anterior Enero Julio)
		(anterior Enero Agosto)
		(anterior Enero Septiembre)
		(anterior Enero Octubre)
		(anterior Enero Noviembre)
		(anterior Enero Diciembre)
		(anterior Febrero Marzo)
		(anterior Febrero Abril)
		(anterior Febrero Mayo)
		(anterior Febrero Junio)
		(anterior Febrero Julio)
		(anterior Febrero Agosto)
		(anterior Febrero Septiembre)
		(anterior Febrero Octubre)
		(anterior Febrero Noviembre)
		(anterior Febrero Diciembre)
		(anterior Marzo Abril)
		(anterior Marzo Mayo)
		(anterior Marzo Junio)
		(anterior Marzo Julio)
		(anterior Marzo Agosto)
		(anterior Marzo Septiembre)
		(anterior Marzo Octubre)
		(anterior Marzo Noviembre)
		(anterior Marzo Diciembre)
		(anterior Abril Mayo)
		(anterior Abril Junio)
		(anterior Abril Julio)
		(anterior Abril Agosto)
		(anterior Abril Septiembre)
		(anterior Abril Octubre)
		(anterior Abril Noviembre)
		(anterior Abril Diciembre)
		(anterior Mayo Junio)
		(anterior Mayo Julio)
		(anterior Mayo Agosto)
		(anterior Mayo Septiembre)
		(anterior Mayo Octubre)
		(anterior Mayo Noviembre)
		(anterior Mayo Diciembre)
		(anterior Junio Julio)
		(anterior Junio Agosto)
		(anterior Junio Septiembre)
		(anterior Junio Octubre)
		(anterior Junio Noviembre)
		(anterior Junio Diciembre)
		(anterior Julio Agosto)
		(anterior Julio Septiembre)
		(anterior Julio Octubre)
		(anterior Julio Noviembre)
		(anterior Julio Diciembre)
		(anterior Agosto Septiembre)
		(anterior Agosto Octubre)
		(anterior Agosto Noviembre)
		(anterior Agosto Diciembre)
		(anterior Septiembre Octubre)
		(anterior Septiembre Noviembre)
		(anterior Septiembre Diciembre)
		(anterior Octubre Noviembre)
		(anterior Octubre Diciembre)
		(anterior Noviembre Diciembre)
		(= (paginas-leidas Enero) 0)
		(= (paginas-leidas Febrero) 0)
		(= (paginas-leidas Marzo) 0)
		(= (paginas-leidas Abril) 0)
		(= (paginas-leidas Mayo) 0)
		(= (paginas-leidas Junio) 0)
		(= (paginas-leidas Julio) 0)
		(= (paginas-leidas Agosto) 0)
		(= (paginas-leidas Septiembre) 0)
		(= (paginas-leidas Octubre) 0)
		(= (paginas-leidas Noviembre) 0)
		(= (paginas-leidas Diciembre) 0)
		; Relaciones entre objetos
		(predecesor Libro0 Libro1)
		(predecesor Libro1 Libro3)
		(predecesor Libro1 Libro4)
		(predecesor Libro1 Libro5)
		(predecesor Libro1 Libro6)
		(predecesor Libro2 Libro3)
		(predecesor Libro2 Libro5)
		(predecesor Libro2 Libro7)
		(predecesor Libro3 Libro9)
		(predecesor Libro4 Libro6)
		(predecesor Libro4 Libro9)
		(predecesor Libro5 Libro6)
		(predecesor Libro5 Libro8)
		(predecesor Libro6 Libro7)
		(predecesor Libro8 Libro9)
		(paralelo Libro2 Libro4) (paralelo Libro4 Libro2)
		(paralelo Libro4 Libro2) (paralelo Libro2 Libro4)
		(= (paginas Libro0) 44)
		(= (paginas Libro1) 87)
		(= (paginas Libro2) 57)
		(= (paginas Libro3) 44)
		(= (paginas Libro4) 97)
		(= (paginas Libro5) 81)
		(= (paginas Libro6) 5)
		(= (paginas Libro7) 15)
		(= (paginas Libro8) 55)
		(= (paginas Libro9) 71)
	)

	(:goal
		; Para todos los libros que se quieren leer, leidos. Para los paralelos a los que se quieren leer, leidos
		(and (forall (?l - quiereL) (asignado ?l))
			 (forall (?l - libro) (imply (exists (?par - quiereL) (paralelo ?par ?l)) (asignado ?l)))
		)
	)
)
